version: '3.2'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_dev

  front:
    build: ./frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /app
    ports:
      - 3000:3000
    depends_on:
      - back
    command: yarn start

  back:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend
        target: /app
    ports:
      - 4000:4000
    environment:
      - DB_PASS=postgres
      - DB_HOST=db
    depends_on:
      - db
    command:
      - ./run.sh
