version: '3.2'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: backend_dev

  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    environment:
      - DB_PASS=postgres
      - DB_HOST=db
    depends_on:
      - db
    command:
      - ./run.sh
